### ISSUE TITLE
Method does not account for duplicate structures

### ISSUE THREAD

**Issue by xaviermartinez2012** [sorinlab/fahda-logfile#1]
https://github.com/sorinlab/fahda-logfile/blob/43036acb3ca04d80996904bce092d0d39c1ddc38/logfile-make.pl#L91-L105

As you know Gromacs has a bug that makes duplicate structures. The method (or subroutine; don't know what they call them in perl) described above would not work as expected if it encounters this bug (from what I am interpreting). Maybe you could try the set data structure (to guarantee uniqueness)?

**Comment by xaviermartinez2012** [comment]
Another suggestion: keep track of the i-1 line and compare the i-th to it. If the two are equal, skip, otherwise append as usual.

**Comment by khaister** [comment]
This will be addressed in #2.
